repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
    -   id: check-docstring-first
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: detect-private-key

-   repo: https://github.com/asottile/add-trailing-comma
    rev: ''
    hooks:
    -   id: add-trailing-comma

-   repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=120]
        language_version: python3
        exclude: ^.*\b(migrations)\b.*$

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
